const fs = require('fs');
let cur = fs.readFileSync('public/script.js', 'utf8');

const corruptedStrings = [
    "document.getElementById('')..display = 'block'",
    "document.getElementById('')..display = 'none'",
    "document.getElementById('')..add('active')",
    "document.getElementById('')..add('active')",
    "document.getElementById('')..remove('active')",
    "document.getElementById('')..remove('active')",
    "document.getElementById('').('click', closeCart)",
    "onclick=\"document.getElementById('').=this.src",
    "onclick=\"document.getElementById('').=this.src",
    "onclick=\"document.getElementById('').=this.src",
    "const rating = document.getElementById('').;",
    "const comment = document.getElementById('').;",
    "document.getElementById(''). = '¡Gracias por tu reseña! Recarga la página para verla.'",
    "document.getElementById('')..display = 'block'",
    "const email = document.getElementById('').;",
    "const name = document.getElementById('').;",
    "const address = document.getElementById('').;",
    "const customer_email = document.getElementById('').;",
    "const customer_name = document.getElementById(''). + ' ' + document.getElementById('').;", // 2 matches
    "const city = document.getElementById('').;",
    "const shipping_address = document.getElementById(''). + ', ' + city + ' CP: ' + document.getElementById('').;", // 2 matches
    "const name = document.getElementById('').;",
    "const email = document.getElementById('').;",
    "const password = document.getElementById('').;",
    "const email = document.getElementById('').;",
    "const password = document.getElementById('').;",
    "formData.append('name', document.getElementById('').)",
    "const baseDesc = document.getElementById('').;",
    "formData.append('price', document.getElementById('').)",
    "formData.append('brand', document.getElementById('').)",
    "formData.append('category', document.getElementById('').)",
    "formData.append('is_offer', document.getElementById('').)",
    "document.getElementById(''). = currentSettings.top_banner || ''",
    "document.getElementById(''). = currentSettings.flash_end_date || ''",
    "document.getElementById(''). = currentSettings.brands_list || ''",
    "document.getElementById(''). = currentSettings.shipping_correo || 8500",
    "document.getElementById(''). = currentSettings.shipping_andreani || 12000",
    "document.getElementById(''). = currentSettings.free_shipping_threshold || 1500000",
    "currentSettings.top_banner = document.getElementById('').;",
    "currentSettings.flash_end_date = document.getElementById('').;",
    "currentSettings.brands_list = document.getElementById('').;",
    "currentSettings.shipping_correo = Number(document.getElementById('').) || 8500;",
    "currentSettings.shipping_andreani = Number(document.getElementById('').) || 12000;",
    "currentSettings.free_shipping_threshold = Number(document.getElementById('').) || 1500000;",
    "title: document.getElementById('').,",
    "subtitle: document.getElementById('').,",
    "link: document.getElementById('').,",
    "image: document.getElementById('').",
    "if(document.getElementById('cd-days')) document.getElementById(''). = days.toString().padStart(2, '0');",
    "if(document.getElementById('cd-hours')) document.getElementById(''). = hours.toString().padStart(2, '0');",
    "if(document.getElementById('cd-mins')) document.getElementById(''). = minutes.toString().padStart(2, '0');",
    "if(document.getElementById('cd-secs')) document.getElementById(''). = seconds.toString().padStart(2, '0');"
];

const correctStrings = [
    "document.getElementById('free-shipping-container').style.display = 'block'",
    "document.getElementById('free-shipping-container').style.display = 'none'",
    "document.getElementById('side-cart').classList.add('active')",
    "document.getElementById('side-cart-overlay').classList.add('active')",
    "document.getElementById('side-cart').classList.remove('active')",
    "document.getElementById('side-cart-overlay').classList.remove('active')",
    "document.getElementById('close-cart-btn').addEventListener('click', closeCart)",
    "onclick=\"document.getElementById('main-product-img').src=this.src",
    "onclick=\"document.getElementById('main-product-img').src=this.src",
    "onclick=\"document.getElementById('main-product-img').src=this.src",
    "const rating = document.getElementById('review-rating').value;",
    "const comment = document.getElementById('review-comment').value;",
    "document.getElementById('review-msg').innerText = '¡Gracias por tu reseña! Recarga la página para verla.'",
    "document.getElementById('review-msg').style.display = 'block'",
    "const email = document.getElementById('chk-email').value;",
    "const name = document.getElementById('chk-name').value;",
    "const address = document.getElementById('chk-address').value;",
    "const customer_email = document.getElementById('chk-email').value;",
    "const customer_name = document.getElementById('chk-name').value + ' ' + document.getElementById('chk-lastname').value;",
    "const city = document.getElementById('chk-city').value;",
    "const shipping_address = document.getElementById('chk-address').value + ', ' + city + ' CP: ' + document.getElementById('chk-zip').value;",
    "const name = document.getElementById('reg-name').value;",
    "const email = document.getElementById('reg-email').value;",
    "const password = document.getElementById('reg-password').value;",
    "const email = document.getElementById('log-email').value;",
    "const password = document.getElementById('log-password').value;",
    "formData.append('name', document.getElementById('prod-name').value)",
    "const baseDesc = document.getElementById('prod-desc').value;",
    "formData.append('price', document.getElementById('prod-price').value)",
    "formData.append('brand', document.getElementById('prod-brand').value)",
    "formData.append('category', document.getElementById('prod-category').value)",
    "formData.append('is_offer', document.getElementById('prod-offer').value)",
    "document.getElementById('set-banner').value = currentSettings.top_banner || ''",
    "document.getElementById('set-flash-date').value = currentSettings.flash_end_date || ''",
    "document.getElementById('set-brands-list').value = currentSettings.brands_list || ''",
    "document.getElementById('set-ship-correo').value = currentSettings.shipping_correo || 8500",
    "document.getElementById('set-ship-andreani').value = currentSettings.shipping_andreani || 12000",
    "document.getElementById('set-free-shipping').value = currentSettings.free_shipping_threshold || 1500000",
    "currentSettings.top_banner = document.getElementById('set-banner').value;",
    "currentSettings.flash_end_date = document.getElementById('set-flash-date').value;",
    "currentSettings.brands_list = document.getElementById('set-brands-list').value;",
    "currentSettings.shipping_correo = Number(document.getElementById('set-ship-correo').value) || 8500;",
    "currentSettings.shipping_andreani = Number(document.getElementById('set-ship-andreani').value) || 12000;",
    "currentSettings.free_shipping_threshold = Number(document.getElementById('set-free-shipping').value) || 1500000;",
    "title: document.getElementById('set-car-title').value,",
    "subtitle: document.getElementById('set-car-subtitle').value,",
    "link: document.getElementById('set-car-link').value,",
    "image: document.getElementById('set-car-img').value",
    "if(document.getElementById('cd-days')) document.getElementById('cd-days').innerText = days.toString().padStart(2, '0');",
    "if(document.getElementById('cd-hours')) document.getElementById('cd-hours').innerText = hours.toString().padStart(2, '0');",
    "if(document.getElementById('cd-mins')) document.getElementById('cd-mins').innerText = minutes.toString().padStart(2, '0');",
    "if(document.getElementById('cd-secs')) document.getElementById('cd-secs').innerText = seconds.toString().padStart(2, '0');"
];

for (let i = 0; i < corruptedStrings.length; i++) {
    cur = cur.replace(corruptedStrings[i], correctStrings[i]);
}

fs.writeFileSync('public/script.js', cur, 'utf8');
console.log('Restored all 54 lines perfectly!');
